version: 2
jobs:
  agent-build:
    docker:
      - image: bcgovimages/von-image:py36-1.9-0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-pip-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements.dev.txt" }}
            - v2-pip-dependencies-{{ .Branch }}-
      - run:
          name: Install Python Dependencies
          command: |
            mkdir test-packages
            pip install \
              --target test-packages \
              -r requirements.txt \
              -r requirements.dev.txt \
              pytest

      - save_cache:
          paths:
            - test-packages
          key: v2-pip-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements.dev.txt" }}

      - run:
          name: Run Agent Tests
          command: |
            mkdir test-reports
            mkdir .coverage
            PYTHONPATH="`pwd`/test-packages:$PYTHONPATH" pytest

      - run:
          name: Push to Codecov.io
          command: |
              bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: test-reports

      - store_test_results:
          path: .coverage

      - store_artifacts:
          path: test-reports

      - store_artifacts:
          path: .coverage

workflows:
 version: 2
 aries_cloudagent:
   jobs:
     - agent-build
