version: 2
jobs:
  agent-build:
    docker:
      - image: bcgovimages/von-image:py36-1.9-0
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-pip-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements.dev.txt" }}
            - v2-pip-dependencies-{{ .Branch }}-
      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install \
              -r requirements.txt \
              -r requirements.dev.txt \
              pytest

      - save_cache:
          paths:
            - venv
          key: v2-pip-dependencies-{{ .Branch }}-{{ checksum "requirements.txt" }}-{{ checksum "requirements.dev.txt" }}

      - run:
          name: Run Agent Tests
          command: |
            mkdir test-reports
            mkdir test-reports/pytest
            . venv/bin/activate
            pytest

      - run:
          name: Push to Codecov.io
          command: |
              bash <(curl -s https://codecov.io/bash)

      - store_test_results:
          path: test-reports

      - store_artifacts:
          path: test-reports

workflows:
 version: 2
 aries_cloudagent:
   jobs:
     - agent-build